export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  PHARMACY_ADMIN = 'PHARMACY_ADMIN',
  PHARMACY_AGENT = 'PHARMACY_AGENT',
  HR_MANAGER = 'HR_MANAGER',
  EMPLOYEE = 'EMPLOYEE',
}

export enum StatementStatus {
  DRAFT = 'DRAFT',
  SENT = 'SENT',
  VALIDATED = 'VALIDATED',
  DISPUTED = 'DISPUTED',
  CLOSED = 'CLOSED',
}

export enum TransactionStatus {
  PENDING = 'PENDING',
  VALIDATED = 'VALIDATED',
  CANCELLED = 'CANCELLED',
}

export enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  EXPORT = 'EXPORT',
  VALIDATE = 'VALIDATE',
}